name: Check for "Good to Merge" label

on:
  pull_request:
    branches:
      - main
    types: [labeled]  # Trigger on PR label changes, PR opened, etc.

jobs:
  check-label:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check for "Good to Merge" label
        run: |
          # Fetch the PR labels
          PR_LABELS=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/labels")

          # Print the labels for debugging purposes
          echo "PR labels: $PR_LABELS"

          # Convert labels to lowercase and check for 'good to merge' label (case-insensitive check)
          PR_LABELS_LOWER=$(echo "$PR_LABELS" | tr '[:upper:]' '[:lower:]')
          
          if [[ "$PR_LABELS_LOWER" != *"good to merge"* ]]; then
            echo "PR does not have the 'Good to Merge' label, failing the workflow."
            exit 1  # Fail the job to block the merge
          else
            echo "PR has the 'Good to Merge' label, passing the workflow."
          fi
