name: Trigger Action on PR Label "Good to Merge"

on:
  pull_request:
    types: [labeled]
    # branches:
    #   - staging
    #   - prod

jobs:
  # check-good-to-merge-label:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Check if the latest added label is 'Good to Merge'
  #       id: check_label
  #       run: |
  #         echo "Checking label: ${{ github.event.label.name }}"
  #         if [ "${{ github.event.label.name }}" == "Good to Merge" ]; then
  #           echo "Label 'Good to Merge' detected. Triggering the next action."
  #         else
  #           echo "Label is not 'Good to Merge'. Skipping."
  #           exit 0
  #         fi

  trigger-other-action:
    # needs: check-good-to-merge-label
    # if: success()
    runs-on: self-hosted
    steps:
      - name: Trigger another action (ktlint-and-unit-tests)
        env:
          GH_TOKEN: ${{ secrets.TOKEN_WITH_SPECIFIC_ACCESS }}
        run: |
          echo "Triggering the 'ktlint-and-unit-tests' action"
          echo "github.repository: ${{ github.repository }}"
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.TOKEN_WITH_SPECIFIC_ACCESS }}" \
            -H "Accept: application/vnd.github.v3+json" \
            --data '{"ref":"${{ github.head_ref }}"}' \
            "https://api.github.com/repos/${{ github.repository }}/actions/workflows/check-draft.yml/dispatches"

      - name: Create a check run for PR
        run: |
          PR_SHA="${{ github.sha }}"  # Get the current commit SHA
          CHECK_RUN_RESPONSE=$(curl -X POST \
            -H "Authorization: Bearer ${{ secrets.TOKEN_WITH_SPECIFIC_ACCESS }}" \
            -d '{
              "name": "ktlint-and-unit-tests",
              "head_sha": "'"$PR_SHA"'",
              "status": "in_progress",
              "output": {
                "title": "Running Lint and Unit Tests",
                "summary": "The workflow is running..."
              }
            }' \
            "https://api.github.com/repos/${{ github.repository }}/check-runs")
          
          # Extract the Check Run ID
          CHECK_RUN_ID=$(echo $CHECK_RUN_RESPONSE | jq -r '.id')
          echo "Check Run ID: $CHECK_RUN_ID"

