name: Trigger Action on PR Label "Good to Merge"

on:
  pull_request:
    types: [labeled]
    # branches:
    #   - staging
    #   - prod

jobs:
  # check-good-to-merge-label:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Check if the latest added label is 'Good to Merge'
  #       id: check_label
  #       run: |
  #         echo "Checking label: ${{ github.event.label.name }}"
  #         if [ "${{ github.event.label.name }}" == "Good to Merge" ]; then
  #           echo "Label 'Good to Merge' detected. Triggering the next action."
  #         else
  #           echo "Label is not 'Good to Merge'. Skipping."
  #           exit 0
  #         fi

  check-jenkins-queue:
    runs-on: self-hosted
    outputs:
      queue_ok: ${{ steps.check_jenkins_queue.outputs.queue_ok }}
    steps:
      - name: Check Jenkins Queue
        id: check_jenkins_queue
        run: |
          QUEUE_COUNT=$(curl -s -u qa-housing:11068328e131d27fc5aab6d7491dc3dfc2 "http://52.221.78.153:8080/queue/api/json" | --jq '[.items[] | select(.task.name=="Android_Generate_coverage_report")] | length')
          echo "queue_count=$QUEUE_COUNT"
          if [ "$QUEUE_COUNT" -lt 5 ]; then
            echo "queue_ok=true" >> $GITHUB_OUTPUT
          else
            echo "queue_ok=false" >> $GITHUB_OUTPUT
          fi

