name: Remove "Good to Merge" Label

on:
  pull_request:
    branches:
      - main  # Specify the branch you want to protect (e.g., `main`, `staging`)
    types: [synchronize]  # Trigger on PR label changes, PR opened, etc.
  push:
    branches:
      - main  # Trigger on push to the `main` branch (or your target branch)
    paths:
      - '**/*'  # Trigger on any change in the repository

jobs: 
  run-fastlane-action:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Trigger Jenkins Job
        env:
          JENKINS_URL: "http://13.250.131.244"
          JENKINS_USER: "qa-housing"
          JENKINS_TOKEN: "11285537b9334c11c92b2cc131ea399300"
          JOB_NAME: "Android_Generate_coverage_report"
          BRANCH: "staging"
        run: |
          echo "Triggering Jenkins job $JOB_NAME for branch $BRANCH"

          # Trigger the Jenkins job with parameters
          RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" \
            -X POST "${JENKINS_URL}/job/${JOB_NAME}/buildWithParameters?branch=${BRANCH}" \
            --user "${JENKINS_USER}:${JENKINS_TOKEN}")

          echo "Jenkins response HTTP code: $RESPONSE"

          if [ "$RESPONSE" -ge 400 ]; then
            echo "❌ Jenkins job trigger failed"
            exit 1
          else
            echo "✅ Jenkins job triggered successfully"
          fi
          
  remove-label:
    permissions:
      contents: write
    runs-on: self-hosted
    
    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # For debugging purpose
      - name: Print data
        run: |
          # Get PR data
          echo "github.event_name ${{ github.event_name }}"
          echo "github.event.action ${{ github.event.action }}"
          echo "check for label ${{ contains(github.event.pull_request.labels.*.name, 'Good to Merge') }}"

      # Step 1: Remove "Good to Merge" label when a commit is pushed or PR is synchronized
      - name: Remove "Good to Merge" label from the PR
        if: contains(github.event.pull_request.labels.*.name, 'Good to Merge')
        run: |
          # Get the PR number associated with the commit
          PR_NUMBER=${{ github.event.pull_request.number }}

          echo "PR number: $PR_NUMBER"

          if [ -z "$PR_NUMBER" ]; then
            echo "No pull request found for this commit."
            exit 0
          fi

          echo "Found PR number: $PR_NUMBER"

          # Remove the "Good to Merge" label from the PR
          curl -s -X DELETE -H "Authorization: token ${{ secrets.TOKEN_WITH_SPECIFIC_ACCESS }}" \
            "https://api.github.com/repos/${{ github.repository }}/issues/$PR_NUMBER/labels/good%20to%20merge"

          echo "Removed 'Good to Merge' label from PR #$PR_NUMBER"
