name: Remove "Good to Merge" Label

on:
  pull_request:
    branches:
      - main  # Specify the branch you want to protect (e.g., `main`, `staging`)
    types: [labeled, synchronize]  # Trigger on PR label changes, PR opened, etc.
  push:
    branches:
      - main  # Trigger on push to the `main` branch (or your target branch)
    paths:
      - '**/*'  # Trigger on any change in the repository

jobs:
  remove-label:
    runs-on: ubuntu-latest
    
    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 1: Remove "Good to Merge" label when a commit is pushed or PR is synchronized
      - name: Remove "Good to Merge" label from the PR
        if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action == 'synchronize')  # Run this for both commit push and synchronize events
        run: |
          # Get the PR number associated with the commit
          # PR_NUMBER=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          #   "https://api.github.com/repos/${{ github.repository }}/commits/${{ github.sha }}/pulls" \
          #   | jq '.[0].number')
          PR_NUMBER=23

          echo "PR number: $PR_NUMBER"

          if [ -z "$PR_NUMBER" ]; then
            echo "No pull request found for this commit."
            exit 0
          fi

          echo "Found PR number: $PR_NUMBER"

          # Remove the "Good to Merge" label from the PR
          curl -s -X DELETE -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/issues/$PR_NUMBER/labels/good%20to%20merge"

          echo "Removed 'Good to Merge' label from PR #$PR_NUMBER"

      # Step 2: Debugging step to confirm the label removal action was triggered (optional)
      - name: Debugging (Check if Label Removed)
        run: |
          PR_LABELS=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/labels")
          echo "PR labels: $PR_LABELS"
