name: Check and Remove "Good to Merge" Label

on:
  pull_request:
    branches:
      - main  # Specify the branch you want to protect (e.g., `main`, `staging`)
    types: [labeled, synchronize]  # Trigger on PR label changes, PR opened, etc.
  push:
    branches:
      - main  # Trigger on push to the `main` branch (or your target branch)
    paths:
      - '**/*'  # Trigger on any change in the repository

jobs:
  check-remove-label:
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Checkout the repository code
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Get PR associated with the commit
      - name: Get PR number associated with the commit
        run: |
          # Fetch the PR associated with the commit using the commit SHA
          PR_NUMBER=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/commits/${{ github.sha }}/pulls" \
            | jq '.[0].number')

          if [ -z "$PR_NUMBER" ]; then
            echo "No pull request found for this commit."
            exit 0
          fi

          echo "Found PR number: $PR_NUMBER"

      # Step 3: Remove "Good to Merge" label when a commit is pushed or PR is synchronized
      - name: Remove "Good to Merge" label from the PR
        if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action == 'synchronize')  # Handle both commit push and synchronize events
        run: |
          echo "Attempting to remove 'Good to Merge' label from PR #$PR_NUMBER"
          
          # Remove the "Good to Merge" label from the PR using the correct API URL
          curl -s -X DELETE -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository
